import { NextResponse } from "next/server";
import { NextRequest } from "next/server";

const PRODUCTS: Record<string, object> = {
  "rattan-table-lamp": { id: 1, name: "Rattan Table Lamp", name_ar: "مصباح طاولة راتان", slug: "rattan-table-lamp", thumbnail: "/images/product-table-lamp.png", description: "Handcrafted rattan table lamp with linen shade. Perfect for bedside tables, desks or side tables. Each piece is unique.", description_ar: "مصباح طاولة راتان مصنوع يدوياً مع غطاء من الكتان. مثالي لطاولات السرير والمكاتب.", base_price: "85.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "variation", product_stock: 15, categories: [{ id: 1, name: "Lighting", slug: "lighting" }], brand: null, gallery: [{ id: 1, image: "/images/product-table-lamp.png", video: null, order: 1 }, { id: 2, image: "/images/product-ceramic-lamp.png", video: null, order: 2 }, { id: 3, image: "/images/product-pendant.png", video: null, order: 3 }, { id: 4, image: "/images/product-lighting.png", video: null, order: 4 }], available_variations: [{ id: 1, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Natural", value_ar: "طبيعي", stock: 8 }, { id: 2, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Dark", value_ar: "داكن", stock: 7 }], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-01T00:00:00Z", updated_at: "2025-01-10T00:00:00Z" },
  "boho-wall-macrame": { id: 2, name: "Boho Wall Macrame", name_ar: "ماكريمي جداري بوهيمي", slug: "boho-wall-macrame", thumbnail: "/images/product-wall-decor.png", description: "Large handmade macrame wall hanging crafted from natural cotton rope. Adds a warm bohemian touch to any space.", description_ar: "ماكريمي جداري كبير مصنوع يدوياً من الحبال القطنية الطبيعية.", base_price: "120.00", discount_price: "95.00", has_discount: true, is_available: true, best_seller: true, inventory_mode: "simple", product_stock: 8, categories: [{ id: 2, name: "Wall Decor", slug: "wall-decor" }], brand: null, gallery: [{ id: 3, image: "/images/product-wall-decor.png", video: null, order: 1 }, { id: 4, image: "/images/product-macrame.png", video: null, order: 2 }, { id: 5, image: "/images/product-fiber-art.png", video: null, order: 3 }, { id: 6, image: "/images/product-bohemian.png", video: null, order: 4 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-02T00:00:00Z", updated_at: "2025-01-11T00:00:00Z" },
};

// Default product for unknown slugs
const DEFAULT_PRODUCT = { id: 1, name: "Artisan Home Piece", name_ar: "قطعة منزلية حرفية", slug: "artisan-piece", thumbnail: "/images/product-table-lamp.png", description: "A beautiful artisan piece for your home.", description_ar: "قطعة حرفية جميلة لمنزلك.", base_price: "95.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 10, categories: [{ id: 1, name: "Home Decor", slug: "home-decor" }], brand: null, gallery: [{ id: 1, image: "/images/product-table-lamp.png", video: null, order: 1 }, { id: 2, image: "/images/product-ceramic-lamp.png", video: null, order: 2 }, { id: 3, image: "/images/product-pendant.png", video: null, order: 3 }, { id: 4, image: "/images/product-rugs.png", video: null, order: 4 }], available_variations: [{ id: 1, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Natural", value_ar: "طبيعي", stock: 5 }, { id: 2, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Dark Brown", value_ar: "بني داكن", stock: 3 }, { id: 3, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Black", value_ar: "أسود", stock: 2 }], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-01T00:00:00Z", updated_at: "2025-01-10T00:00:00Z" };

export async function GET(req: NextRequest, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const product = PRODUCTS[slug] || { ...DEFAULT_PRODUCT, slug, name: slug.replace(/-/g, " ").replace(/\b\w/g, l => l.toUpperCase()) };
  return NextResponse.json(product);
}
