import { NextResponse } from "next/server";

const products = [
  { id: 1, name: "Rattan Table Lamp", name_ar: "مصباح طاولة راتان", slug: "rattan-table-lamp", thumbnail: "/images/product-table-lamp.png", description: "Handcrafted rattan table lamp with linen shade. Perfect for any room.", description_ar: "مصباح طاولة راتان مصنوع يدوياً مع غطاء من الكتان.", base_price: "85.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "variation", product_stock: 15, categories: [{ id: 1, name: "Lighting", slug: "lighting" }], brand: null, gallery: [{ id: 1, image: "/images/product-table-lamp.png", video: null, order: 1 }, { id: 2, image: "/images/product-ceramic-lamp.png", video: null, order: 2 }], available_variations: [{ id: 1, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Natural", value_ar: "طبيعي", stock: 8 }, { id: 2, attribute: { id: 1, name: "Color", name_ar: "اللون" }, value: "Dark", value_ar: "داكن", stock: 7 }], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-01T00:00:00Z", updated_at: "2025-01-10T00:00:00Z" },
  { id: 2, name: "Boho Wall Macrame", name_ar: "ماكريمي جداري بوهيمي", slug: "boho-wall-macrame", thumbnail: "/images/product-wall-decor.png", description: "Large handmade macrame wall hanging with natural cotton rope.", description_ar: "ماكريمي جداري كبير مصنوع يدوياً من الحبال القطنية الطبيعية.", base_price: "120.00", discount_price: "95.00", has_discount: true, is_available: true, best_seller: true, inventory_mode: "simple", product_stock: 8, categories: [{ id: 2, name: "Wall Decor", slug: "wall-decor" }], brand: null, gallery: [{ id: 3, image: "/images/product-wall-decor.png", video: null, order: 1 }, { id: 4, image: "/images/product-macrame.png", video: null, order: 2 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-02T00:00:00Z", updated_at: "2025-01-11T00:00:00Z" },
  { id: 3, name: "Woven Pendant Light", name_ar: "مصباح معلق منسوج", slug: "woven-pendant-light", thumbnail: "/images/product-pendant.png", description: "Natural fiber woven pendant lamp, handcrafted by artisans.", description_ar: "مصباح معلق منسوج من الألياف الطبيعية، مصنوع يدوياً.", base_price: "140.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 6, categories: [{ id: 1, name: "Lighting", slug: "lighting" }], brand: null, gallery: [{ id: 5, image: "/images/product-pendant.png", video: null, order: 1 }, { id: 6, image: "/images/product-lighting.png", video: null, order: 2 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-03T00:00:00Z", updated_at: "2025-01-12T00:00:00Z" },
  { id: 4, name: "Quilted Pouches Set", name_ar: "طقم حقائب مبطنة", slug: "quilted-pouches", thumbnail: "/images/product-bags.png", description: "Set of 2 handmade quilted cotton pouches with block print design.", description_ar: "طقم من حقيبتين من القطن المبطن المطبوع يدوياً.", base_price: "65.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 20, categories: [{ id: 3, name: "Bags", slug: "bags" }], brand: null, gallery: [{ id: 7, image: "/images/product-bags.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-04T00:00:00Z", updated_at: "2025-01-13T00:00:00Z" },
  { id: 5, name: "Artisan Pendant Lamp", name_ar: "مصباح حرفي معلق", slug: "artisan-pendant-lamp", thumbnail: "/images/product-lighting.png", description: "Dual rattan pendant lamps, perfect for dining rooms and living spaces.", description_ar: "مصابيح معلقة مزدوجة من الراتان، مثالية لغرف الطعام.", base_price: "195.00", discount_price: "160.00", has_discount: true, is_available: true, best_seller: true, inventory_mode: "simple", product_stock: 4, categories: [{ id: 1, name: "Lighting", slug: "lighting" }], brand: null, gallery: [{ id: 8, image: "/images/product-lighting.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-05T00:00:00Z", updated_at: "2025-01-14T00:00:00Z" },
  { id: 6, name: "Globe Pendant Lamp", name_ar: "مصباح كروي معلق", slug: "globe-pendant-lamp", thumbnail: "/images/product-globe-lamp.png", description: "Sculptural textured globe pendant, statement piece for any room.", description_ar: "مصباح كروي منحوت، قطعة مميزة لأي غرفة.", base_price: "210.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 3, categories: [{ id: 1, name: "Lighting", slug: "lighting" }], brand: null, gallery: [{ id: 9, image: "/images/product-globe-lamp.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-06T00:00:00Z", updated_at: "2025-01-15T00:00:00Z" },
  { id: 7, name: "Boho Shelf Decor Set", name_ar: "طقم ديكور رف بوهيمي", slug: "boho-shelf-decor", thumbnail: "/images/product-bohemian.png", description: "Curated collection of bohemian shelf decor including baskets, macrame and plants.", description_ar: "مجموعة ديكور رف بوهيمي تشمل سلالاً وماكريمي ونباتات.", base_price: "75.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 12, categories: [{ id: 4, name: "Decor", slug: "decor" }], brand: null, gallery: [{ id: 10, image: "/images/product-bohemian.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-07T00:00:00Z", updated_at: "2025-01-16T00:00:00Z" },
  { id: 8, name: "Macrame Vase Set", name_ar: "طقم إناء ماكريمي", slug: "macrame-vase-set", thumbnail: "/images/product-macrame.png", description: "Handwoven macrame wall art paired with earthy terracotta vase.", description_ar: "فن جداري ماكريمي منسوج يدوياً مع إناء ترا كوتا.", base_price: "90.00", discount_price: "72.00", has_discount: true, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 7, categories: [{ id: 2, name: "Wall Decor", slug: "wall-decor" }], brand: null, gallery: [{ id: 11, image: "/images/product-macrame.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-08T00:00:00Z", updated_at: "2025-01-17T00:00:00Z" },
  { id: 9, name: "Gallery Wall Art Set", name_ar: "طقم لوحات جدارية", slug: "gallery-wall-art", thumbnail: "/images/product-gallery-wall.png", description: "Curated gallery wall set with prints and macrame for eclectic spaces.", description_ar: "طقم لوحات جدارية مع طباعات وماكريمي.", base_price: "155.00", discount_price: null, has_discount: false, is_available: true, best_seller: true, inventory_mode: "simple", product_stock: 5, categories: [{ id: 2, name: "Wall Decor", slug: "wall-decor" }], brand: null, gallery: [{ id: 12, image: "/images/product-gallery-wall.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-09T00:00:00Z", updated_at: "2025-01-18T00:00:00Z" },
  { id: 10, name: "Fiber Art Wall Piece", name_ar: "لوحة فنية جدارية", slug: "fiber-art-wall", thumbnail: "/images/product-fiber-art.png", description: "Large woven fiber art wall installation, natural tones and textures.", description_ar: "تركيب فني جداري منسوج كبير بألوان وملمس طبيعيين.", base_price: "180.00", discount_price: "145.00", has_discount: true, is_available: true, best_seller: false, inventory_mode: "simple", product_stock: 4, categories: [{ id: 2, name: "Wall Decor", slug: "wall-decor" }], brand: null, gallery: [{ id: 13, image: "/images/product-fiber-art.png", video: null, order: 1 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-10T00:00:00Z", updated_at: "2025-01-19T00:00:00Z" },
  { id: 11, name: "Natural Jute Rug", name_ar: "سجادة جوت طبيعية", slug: "natural-jute-rug", thumbnail: "/images/product-rugs.png", description: "Hand-knotted natural jute rug, adds warmth and texture to any space.", description_ar: "سجادة جوت طبيعية معقودة يدوياً تضيف الدفء والملمس.", base_price: "220.00", discount_price: null, has_discount: false, is_available: true, best_seller: false, inventory_mode: "combination", product_stock: 10, categories: [{ id: 5, name: "Rugs", slug: "rugs" }], brand: null, gallery: [{ id: 14, image: "/images/product-rugs.png", video: null, order: 1 }], available_variations: [], available_combinations: [{ id: 1, label: "120×180cm", attributes: [{ attribute: { id: 2, name: "Size", name_ar: "المقاس" }, value: "120×180cm", value_ar: "120×180سم" }], stock: 5 }, { id: 2, label: "160×230cm", attributes: [{ attribute: { id: 2, name: "Size", name_ar: "المقاس" }, value: "160×230cm", value_ar: "160×230سم" }], stock: 5 }], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-11T00:00:00Z", updated_at: "2025-01-20T00:00:00Z" },
  { id: 12, name: "Ceramic Table Lamp", name_ar: "مصباح طاولة سيراميك", slug: "ceramic-table-lamp", thumbnail: "/images/product-ceramic-lamp.png", description: "Glazed ceramic base table lamp with warm amber hue, creates cozy atmosphere.", description_ar: "مصباح طاولة بقاعدة سيراميك مزجج بلون كهرماني دافئ.", base_price: "110.00", discount_price: "88.00", has_discount: true, is_available: true, best_seller: true, inventory_mode: "simple", product_stock: 9, categories: [{ id: 1, name: "Lighting", slug: "lighting" }], brand: null, gallery: [{ id: 15, image: "/images/product-ceramic-lamp.png", video: null, order: 1 }, { id: 16, image: "/images/product-table-lamp.png", video: null, order: 2 }], available_variations: [], available_combinations: [], currency_info: { code: "JOD", symbol: "JD", exchange_rate: "1.000" }, created_at: "2025-01-12T00:00:00Z", updated_at: "2025-01-21T00:00:00Z" },
];

export async function GET(req: Request) {
  const url = new URL(req.url);
  const search = url.searchParams.get("search")?.toLowerCase();
  const page = parseInt(url.searchParams.get("page") || "1");
  const pageSize = parseInt(url.searchParams.get("page_size") || "12");
  const categorySlug = url.searchParams.get("category_slug");
  const bestSeller = url.searchParams.get("best_seller");
  const ordering = url.searchParams.get("ordering");
  const priceMin = parseFloat(url.searchParams.get("price_min") || "0");
  const priceMax = parseFloat(url.searchParams.get("price_max") || "999999");

  let filtered = [...products];
  if (search) filtered = filtered.filter(p => p.name.toLowerCase().includes(search) || p.name_ar.includes(search));
  if (categorySlug) filtered = filtered.filter(p => p.categories.some(c => c.slug === categorySlug));
  if (bestSeller === "true") filtered = filtered.filter(p => p.best_seller);
  filtered = filtered.filter(p => parseFloat(p.base_price) >= priceMin && parseFloat(p.base_price) <= priceMax);
  if (ordering === "base_price") filtered.sort((a, b) => parseFloat(a.base_price) - parseFloat(b.base_price));
  else if (ordering === "-base_price") filtered.sort((a, b) => parseFloat(b.base_price) - parseFloat(a.base_price));
  else if (ordering === "-created_at") filtered.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  else if (ordering === "best_seller") filtered = filtered.filter(p => p.best_seller);

  const total = filtered.length;
  const start = (page - 1) * pageSize;
  const results = filtered.slice(start, start + pageSize);

  return NextResponse.json({
    count: total,
    next: start + pageSize < total ? `?page=${page + 1}` : null,
    previous: page > 1 ? `?page=${page - 1}` : null,
    results,
  });
}
